- name: Manage DNSzone
  hosts: dns_gandi
  gather_facts: no
  roles:
    - role: roles/zoneDNS
  tags: gandi

- name: Manage hosting VM
  hosts: switchvm
  gather_facts: no
  roles:
    - role: roles/hosting
  tags: vm
