- include_vars: zoneDNS-vars.yml
  tags: always

- name: Print gandi API key
  ansible.builtin.debug:
    msg: "Gandi API key is {{ fsdteam_secrets.gandiAPIkey }}"
  tags: always

- name: Create the “www.fsd.team” record to 86.119.37.202
  community.general.gandi_livedns:
    domain: fsd.team
    record: www
    type: A
    values:
      - 86.119.37.202
    ttl: 300
    api_key: "{{ fsdteam_secrets.gandiAPIkey }}"
  register: record
  tags: www

- name: Create the “fsd.team” record to 86.119.37.202
  community.general.gandi_livedns:
    domain: fsd.team
    record: fsd.team
    type: A
    values:
      - 86.119.37.202
    ttl: 300
    api_key: "{{ fsdteam_secrets.gandiAPIkey }}"
  register: record
  tags: www

- name: Create the “dev” A record to point to localhost
  community.general.gandi_livedns:
    domain: fsd.team
    record: dev
    type: A
    values:
      - 127.0.0.1
    ttl: 7200
    api_key: "{{ fsdteam_secrets.gandiAPIkey }}"
  register: record
  tags: dev

- name: Create the “*.dev” A record to point to localhost
  community.general.gandi_livedns:
    domain: fsd.team
    record: "*.dev"
    type: A
    values:
      - 127.0.0.1
    ttl: 7200
    api_key: "{{ fsdteam_secrets.gandiAPIkey }}"
  register: record
  tags: star

- name: Create the ”noc.fsd.team” record to 86.119.37.70
  community.general.gandi_livedns:
    domain: fsd.team
    record: noc
    type: A
    values:
      - 86.119.37.70
    ttl: 300
    api_key: "{{ fsdteam_secrets.gandiAPIkey }}"
  tags: noc

- name: Create the “*.noc” CNAME record to point to *.noc.fsd.team
  community.general.gandi_livedns:
    domain: fsd.team
    record: "*.noc"
    type: CNAME
    values:
      - noc
    ttl: 300
    api_key: "{{ fsdteam_secrets.gandiAPIkey }}"
  tags: noc

- name: Create the ”noc-test.fsd.team” record to 86.119.39.25
  community.general.gandi_livedns:
    domain: fsd.team
    record: noc-test
    type: A
    values:
      - 86.119.39.25
    ttl: 300
    api_key: "{{ fsdteam_secrets.gandiAPIkey }}"
  tags:
    - noc
    - noc-test

- name: Create the “*.noc-test” CNAME record to point to *.noc-test.fsd.team
  community.general.gandi_livedns:
    domain: fsd.team
    record: "*.noc-test"
    type: CNAME
    values:
      - noc-test
    ttl: 300
    api_key: "{{ fsdteam_secrets.gandiAPIkey }}"
  tags:
    - noc
    - noc-test

- name: Ensure DNS records for canap test and staging environments
  community.general.gandi_livedns:
    domain: fsd.team
    record: "{{ item.record }}"
    type: "{{ item.type | default('A') }}"
    state: "{{ item.state | default('present') }}"
    values:
      - "{{ item.value }}"
    ttl: 300
    api_key: "{{ fsdteam_secrets.gandiAPIkey }}"
  with_items:
    - record: canap-test-vm
      value: 10.95.96.134
    - record: canap-prod-vm
      value: 128.178.218.242
    - record: canap
      value: canap-test-vm
      type: CNAME
    - record: pcanap
      value: canap-prod-vm
      type: CNAME
    # - record: canap-gest
    #   value: canap-test-vm
    #   type: CNAME
    #   state: absent
  tags:
    - canap

- name: Ensure DNS records for new EPFL people
  community.general.gandi_livedns:
    domain: fsd.team
    record: "{{ item.record }}"
    type: "{{ item.type | default('A') }}"
    state: "{{ item.state | default('present') }}"
    values:
      - "{{ item.value }}"
    ttl: 1800
    api_key: "{{ fsdteam_secrets.gandiAPIkey }}"
  tags:
    - peonext
  with_items:
    - record: peonext
      value: itspeopl0003.xaas.epfl.ch.
      type: CNAME
    - record: peofik
      value: peonext
      type: CNAME
    - record: peoak
      value: peonext
      type: CNAME

- name: Ensure DNS records electronic voting
  community.general.gandi_livedns:
    domain: fsd.team
    record: "{{ item.record }}"
    type: "{{ item.type | default('A') }}"
    state: "{{ item.state | default('present') }}"
    values:
      - "{{ item.value }}"
    ttl: 300
    api_key: "{{ fsdteam_secrets.gandiAPIkey }}"
  with_items:
    - record: ev03
      value: 10.95.96.145
    - record: ev04
      value: 10.95.96.146
    - record: ev05
      value: 10.95.96.147
    - record: ev06
      value: 10.95.96.148
    - record: ev08
      value: 10.95.96.167
    - record: ev09
      value: 10.95.96.166
    - record: ev10
      value: 10.95.96.173
    - record: ev11
      value: 10.95.96.174

    - record: evdemo
      value: ev03
      type: CNAME

    - record: dvoting
      value: ev03
      type: CNAME

    - record: evprodtraefik
      value: ev08
      type: CNAME

    - record: evdemotraefik
      value: ev03
      type: CNAME

    - record: evdemo1
      value: ev03
      type: CNAME
    - record: evdemo2
      value: ev04
      type: CNAME
    - record: evdemo3
      value: ev05
      type: CNAME
    - record: evdemo4
      value: ev06
      type: CNAME

    - record: evdemo1n
      value: ev03
      type: CNAME
    - record: evdemo2n
      value: ev04
      type: CNAME
    - record: evdemo3n
      value: ev05
      type: CNAME
    - record: evdemo4n
      value: ev06
      type: CNAME
  tags:
    - evoting

- name: Create the ”wpleo.fsd.team” record to 86.119.27.175
  community.general.gandi_livedns:
    domain: fsd.team
    record: wpleo
    type: A
    values:
      - 86.119.27.175
    ttl: 300
    api_key: "{{ fsdteam_secrets.gandiAPIkey }}"
  tags: 
    - wpleo

- name: Create the ”lhd-test.fsd.team” record
  community.general.gandi_livedns:
    domain: fsd.team
    record: lhd-test
    type: A
    values:
      - 128.178.109.25
    ttl: 300
    api_key: "{{ fsdteam_secrets.gandiAPIkey }}"
  tags:
    - lhd

- name: Create the ”mastodon-test.fsd.team” record to 86.119.28.138
  community.general.gandi_livedns:
    domain: fsd.team
    record: mastodon-test
    type: A
    values:
      - 86.119.28.138
    ttl: 300
    api_key: "{{ fsdteam_secrets.gandiAPIkey }}"
  tags: 
    - mastodon
    - mastodon-test

- name: Create the ”gitlab-k8s-api.fsd.team” record to control plane nodes
  community.general.gandi_livedns:
    domain: fsd.team
    record: gitlab-k8s-api
    type: A
    values:
      - 128.178.218.115
      - 128.178.218.231
      - 128.178.218.232
    ttl: 300
    api_key: "{{ fsdteam_secrets.gandiAPIkey }}"
  tags: 
    - gitlab

- name: "wpn.fsd.team"
  community.general.gandi_livedns:
    domain: fsd.team
    record: "wpn"
    type: A
    values:
      - 10.95.96.118
    ttl: 300
    api_key: "{{ fsdteam_secrets.gandiAPIkey }}"
  tags:
    - wp-next
    - wpn

- name: "*.wpn.fsd.team"
  community.general.gandi_livedns:
    domain: fsd.team
    record: "*.wpn"
    type: A
    values:
      - 10.95.96.118
    ttl: 300
    api_key: "{{ fsdteam_secrets.gandiAPIkey }}"
  tags:
    - wp-next
    - wpn

- name: "*.apps.okd-test.fsd.team"
  community.general.gandi_livedns:
    domain: fsd.team
    record: "*.apps.okd-test"
    type: A
    values:
      # This is the IP of itswbhst0025
      - 10.95.96.118
    ttl: 300
    api_key: "{{ fsdteam_secrets.gandiAPIkey }}"
  tags:
    - okd

- name: "api{,-int}.okd-test.fsd.team"
  community.general.gandi_livedns:
    domain: fsd.team
    record: "{{ item }}.okd-test"
    type: A
    values:
      # This is the IP of itswbhst0025
      - 10.95.96.118
    ttl: 300
    api_key: "{{ fsdteam_secrets.gandiAPIkey }}"
  tags:
    - okd
  with_items:
    - api-int   # For access from within OpenShift
    - api       # For access with kubectl / oc etc. from the operator's workstation
