- include_vars: zoneDNS-vars.yml
  tags: always

- name: Print gandi API key
  ansible.builtin.debug:
    msg: "Gandi API key is {{ fsdteam_secrets.gandiAPIkey }}"
  tags: always

- name: Create the “www” record to 86.119.37.202
  community.general.gandi_livedns:
    domain: fsd.team
    record: www
    type: A
    values:
      - 86.119.37.202
    ttl: 300
    api_key: "{{ fsdteam_secrets.gandiAPIkey }}"
  register: record
  tags: www

- name: Alias “*.fsd.team” to www.fsd.team
  community.general.gandi_livedns:
    domain: fsd.team
    record: '*'
    type: CNAME
    values:
      - www
    ttl: 300
    api_key: "{{ fsdteam_secrets.gandiAPIkey }}"
    state: present
  tags: test

# - name: Create the “@” record to 86.119.37.202
#   community.general.gandi_livedns:
#     domain: fsd.team
#     record: '@'
#     type: A
#     values:
#       - 86.119.37.202
#     ttl: 300
#     api_key: "{{ fsdteam_secrets.gandiAPIkey }}"
#   register: record
#   tags: www
# 
# - name: Create the “*” record to 86.119.37.202
#   community.general.gandi_livedns:
#     domain: fsd.team
#     record: '*'
#     type: A
#     values:
#       - 86.119.37.202
#     ttl: 300
#     api_key: "{{ fsdteam_secrets.gandiAPIkey }}"
#   register: record
#   tags: www

- name: Create the “dev” A record to point to localhost
  community.general.gandi_livedns:
    domain: fsd.team
    record: dev
    type: A
    values:
    - 127.0.0.1
    ttl: 7200
    api_key: "{{ fsdteam_secrets.gandiAPIkey }}"
  register: record
  tags: dev

- name: Create the “*.dev” A record to point to localhost
  community.general.gandi_livedns:
    domain: fsd.team
    record: "*.dev"
    type: A
    values:
    - 127.0.0.1
    ttl: 7200
    api_key: "{{ fsdteam_secrets.gandiAPIkey }}"
  register: record
  tags: star

- name: Create a mail CNAME record to specific domain
  community.general.gandi_livedns:
    domain: fsd.team
    record: test
    type: CNAME
    values:
    - dev
    ttl: 7200
    api_key: "{{ fsdteam_secrets.gandiAPIkey }}"
    state: present
  tags: test
