- include_vars: zoneDNS-vars.yml
  tags: always

- name: Print gandi API key
  ansible.builtin.debug:
    msg: "Gandi API key is {{ fsdteam_secrets.gandiAPIkey }}"
  tags: always

- name: Create the “www.fsd.team” record to 86.119.37.202
  community.general.gandi_livedns:
    domain: fsd.team
    record: www
    type: A
    values:
      - 86.119.37.202
    ttl: 300
    api_key: "{{ fsdteam_secrets.gandiAPIkey }}"
  register: record
  tags: www

- name: Create the “fsd.team” record to 86.119.37.202
  community.general.gandi_livedns:
    domain: fsd.team
    record: fsd.team
    type: A
    values:
      - 86.119.37.202
    ttl: 300
    api_key: "{{ fsdteam_secrets.gandiAPIkey }}"
  register: record
  tags: www

- name: Create the “dev” A record to point to localhost
  community.general.gandi_livedns:
    domain: fsd.team
    record: dev
    type: A
    values:
    - 127.0.0.1
    ttl: 7200
    api_key: "{{ fsdteam_secrets.gandiAPIkey }}"
  register: record
  tags: dev

- name: Create the “*.dev” A record to point to localhost
  community.general.gandi_livedns:
    domain: fsd.team
    record: "*.dev"
    type: A
    values:
    - 127.0.0.1
    ttl: 7200
    api_key: "{{ fsdteam_secrets.gandiAPIkey }}"
  register: record
  tags: star

- name: Create the ”noc.fsd.team” record to 86.119.37.70
  community.general.gandi_livedns:
    domain: fsd.team
    record: noc
    type: A
    values:
      - 86.119.37.70
    ttl: 300
    api_key: "{{ fsdteam_secrets.gandiAPIkey }}"
  tags: noc

- name: Create the “*.noc” CNAME record to point to *.noc.fsd.team
  community.general.gandi_livedns:
    domain: fsd.team
    record: "*.noc"
    type: CNAME
    values:
      - noc
    ttl: 300
    api_key: "{{ fsdteam_secrets.gandiAPIkey }}"
  tags: noc

- name: Create the ”noc-test.fsd.team” record to 86.119.39.25
  community.general.gandi_livedns:
    domain: fsd.team
    record: noc-test
    type: A
    values:
      - 86.119.39.25
    ttl: 300
    api_key: "{{ fsdteam_secrets.gandiAPIkey }}"
  tags: 
    - noc
    - noc-test

- name: Create the “*.noc-test” CNAME record to point to *.noc-test.fsd.team
  community.general.gandi_livedns:
    domain: fsd.team
    record: "*.noc-test"
    type: CNAME
    values:
      - noc-test
    ttl: 300
    api_key: "{{ fsdteam_secrets.gandiAPIkey }}"
  tags: 
    - noc
    - noc-test

- name: Ensure DNS records for canap test and staging environments
  community.general.gandi_livedns:
    domain: fsd.team
    record: "{{ item.record }}"
    type: "{{ item.type | default('A') }}"
    state: "{{ item.state | default('present') }}"
    values:
      - "{{ item.value }}"
    ttl: 300
    api_key: "{{ fsdteam_secrets.gandiAPIkey }}"
  with_items:
    - record: canap-test-vm
      value: 10.95.96.134
    - record: canap-prod-vm
      value: 128.178.218.242
    - record: canap
      value: canap-test-vm
      type: CNAME
    - record: pcanap
      value: canap-prod-vm
      type: CNAME
    # - record: canap-gest
    #   value: canap-test-vm
    #   type: CNAME
    #   state: absent
  tags: 
    - canap

- name: Ensure DNS records electronic voting
  community.general.gandi_livedns:
    domain: fsd.team
    record: "{{ item.record }}"
    type: "{{ item.type | default('A') }}"
    state: "{{ item.state | default('present') }}"
    values:
      - "{{ item.value }}"
    ttl: 300
    api_key: "{{ fsdteam_secrets.gandiAPIkey }}"
  with_items:
    - record: ev03
      value: 10.95.96.145
    - record: ev04
      value: 10.95.96.146
    - record: ev05
      value: 10.95.96.147
    - record: ev06
      value: 10.95.96.148
    - record: ev08
      value: 10.95.96.167
    - record: ev09
      value: 10.95.96.166
    - record: ev10
      value: 10.95.96.173
    - record: ev11
      value: 10.95.96.174

    - record: evdemo
      value: ev08
      type: CNAME

    - record: evdemo1
      value: ev08
      type: CNAME
    - record: evdemo2
      value: ev09
      type: CNAME
    - record: evdemo3
      value: ev10
      type: CNAME
    - record: evdemo4
      value: ev08
      type: CNAME

    - record: evdemo1n
      value: ev08
      type: CNAME
    - record: evdemo2n
      value: ev09
      type: CNAME
    - record: evdemo3n
      value: ev10
      type: CNAME
    - record: evdemo4n
      value: ev08
      type: CNAME
  tags: 
    - evoting
